SistemaFinanceiro/Controllers/AcessoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaFinanceiro.Models;

namespace SistemaFinanceiro.Controllers
{
    public class AcessoController : Controller
    {
        private AppDbContext _Context;

        public AcessoController(AppDbContext context)
        {
            _Context = context;
        }

       #region Index, Logging, Logout

        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Entrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Entrar(AcessoModel model, string returnUrl)
        {

            var usuario = _Context.Usuario.FirstOrDefault(c => c.Email == model.Email && c.Senha == model.Senha);

            if (usuario == null)
            {
                ViewBag.Messagen = "Usúario ou senha invalido.";
                ViewBag.returUrl = returnUrl;
                return View(model);
            }

            var claims = new List<Claim>
                {
                    new Claim("sub", usuario.Id.ToString()),
                    new Claim("user", usuario.Email),
                    new Claim("name", usuario.Nome),
                    new Claim("email", usuario.Email)
                };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(new ClaimsIdentity(claims, "Cookies", "user", "role")),
                new AuthenticationProperties
                {
                    IsPersistent = true
                });


            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return Redirect("Index");
            }

        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Entrar");
        }


        #endregion

        #region Usuario

        public ActionResult Usuario()
        {
            return View();
        }

        //Modelo de grids
        public IActionResult UsuarioGrid(string search)
        {

            return PartialView(string.IsNullOrWhiteSpace(search) ? _Context.Usuario.AsQueryable() : _Context.Usuario.Where(c =>
                c.Nome.Contains(search) ||
                c.Email.Contains(search)));
        }

        // GET: Usuario/Edit/5
        public ActionResult UsuarioEdit(int? id)
        {
            if (id > 0)
            {
                return View(_Context.Usuario.Find(id));
            }
            else
            {
                return View(new Usuario());
            }
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UsuarioEdit(Usuario usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (usuario.Id > 0)
                    {
                        var persertir = _Context.Usuario.Find(usuario.Id);

                        persertir.Nome = usuario.Nome;
                        persertir.Email = usuario.Email;
                        persertir.Senha = usuario.Senha;

                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        var validacao = _Context.Usuario.FirstOrDefault(c => c.Email == usuario.Email);

                        if (validacao != null)
                        {
                            ViewBag.Messagen = "Não foi possivel cadastrar Email, já é cadastrado na nossa base";
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            _Context.Usuario.Add(usuario);
                            _Context.SaveChanges();
                        }

                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    return View(usuario);
                }

            }
            catch
            {
                return View(usuario);
            }
        }

        public ActionResult UsuarioDelete(int id)
        {

            var persertir = _Context.Usuario.Find(id);
            _Context.Usuario.Remove(persertir);
            _Context.SaveChanges();

            return RedirectToAction("Usuario");

        }

        #endregion

        #region Terceiros

        public ActionResult Terceiros()
        {
            return View(_Context.Terceiros.ToList());
        }

        //Modelo de grids
        public IActionResult TerceirosGrid(string search)
        {
            return PartialView(string.IsNullOrWhiteSpace(search) ? _Context.Terceiros.AsQueryable() : _Context.Terceiros.Where(c =>
                c.Nome.Contains(search) || c.Cpf.Contains(search) || c.Endereco.Contains(search) || c.Cpf.Contains(search)));

        }

        // GET: Terceiros/Edit/5
        public ActionResult TerceirosEdit(int? id)
        {
            if (id > 0)
            {
                var terceiros = _Context.Terceiros.Include(c => c.ListaDeFinanceriros).FirstOrDefault(c => c.Id == id);
                return View(terceiros);
            }
            else
            {
                return View(new Terceiros());
            }
        }

        // POST: Terceiros/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TerceirosEdit(Terceiros terceiros)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (terceiros.Id > 0)
                    {
                        _Context.Entry(terceiros).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                        _Context.Entry(terceiros).Property(x => x.DataCadastro).IsModified = false;
                        _Context.SaveChanges();

                        return RedirectToAction("Terceiros");
                    }
                    else
                    {
                        terceiros.DataCadastro = DateTime.Now;
                        _Context.Terceiros.Add(terceiros);
                        _Context.SaveChanges();

                        return RedirectToAction("Terceiros");
                    }
                }
                else
                {
                    return View(terceiros);
                }

            }
            catch (Exception ex)
            {
                return View(terceiros);
            }
        }


        public ActionResult TerceirosDelete(int id)
        {

            var persertir = _Context.Terceiros.Find(id);
            _Context.Terceiros.Remove(persertir);
            _Context.SaveChanges();

            return RedirectToAction("Terceiros");

        }

        #endregion

        #region Financeiro

        // GET: Financeiro
        public ActionResult Financeiro()
        {
            return View(_Context.Financeriros.ToList());
        }

        //Modelo de grids
        public IActionResult FinanceiroGrid(string search)
        {
            return PartialView(string.IsNullOrWhiteSpace(search) ? _Context.Financeriros.AsQueryable() : _Context.Financeriros.Where(c =>
                c.Descricao.Contains(search) || c.Terceiros.Id.ToString().Contains(search) || c.DataCadastro.ToString().Contains(search) || c.Valor.ToString().Contains(search)));

        }


        // GET: Financeiro/Edit/5
        public ActionResult FinanceiroEdit(int? id)
        {
            AjusteContextoEditar();

            if (id > 0)
            {
                return View(_Context.Financeriros.Find(id));
            }
            else
            {
                return View(new Financeriros());
            }
        }

        // POST: Financeiro/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FinanceiroEdit(Financeriros terceiros)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (terceiros.Id > 0)
                    {
                        _Context.Entry(terceiros).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                        _Context.Entry(terceiros).Property(x => x.DataCadastro).IsModified = false;
                        _Context.SaveChanges();

                        return RedirectToAction("Financeiro");
                    }
                    else
                    {
                        terceiros.DataCadastro = DateTime.Now;
                        _Context.Financeriros.Add(terceiros);
                        _Context.SaveChanges();

                        return RedirectToAction("Financeiro");
                    }
                }
                else
                {
                    AjusteContextoEditar();
                    return View(terceiros);
                }

            }
            catch (Exception ex)
            {
                AjusteContextoEditar();
                return View(terceiros);
            }
        }


        public ActionResult FinanceiroDelete(int id)
        {

            var persertir = _Context.Financeriros.Find(id);
            _Context.Financeriros.Remove(persertir);
            _Context.SaveChanges();

            return RedirectToAction("Financeiro");

        }

        private void AjusteContextoEditar()
        {
            var terceiros = _Context.Terceiros.ToList();

SistemaFinanceiro/Views/Shared/_Contato.cshtml
<section id="contato" class="container-fluid">
    <div class="container">
        <div class="section-title col-sm-12"><h3><span>Fale Conosco</span></h3></div>
        <div class="home-contato-info text-center col-md-12 hidden-sm hidden-xs"><span>Nossos canais de counicação estão sempre disponíveis: Mande-nos um email que teremos prazer em respondê-lo.</span></div>
        <div class="contato-itens col-xs-12 row slickFal">
            <div class="contato-item col-sm-4 col-xs-12 col-lg-4">
                <div class="home-contato-sac">
                    <a href="mailto:example@example.com" target="_new">
                        <i class="home-contato-icon glyphicon glyphicon-phone center-block text-center"></i>
                        <h5 class="home-contato-title home-fale-title text-center">SAC</h5>
                        <span class="home-contato-text center-block text-center">example@example.com</span>
                    </a>
                </div>
            </div>
            <div class="contato-item col-sm-4 col-xs-12 col-lg-4">
                <div class="home-contato-sac">
                    <a href="mailto:example@example.com" target="_new">
                        <i class="home-contato-icon glyphicon glyphicon-briefcase center-block text-center"></i>
                        <h5 class="home-contato-title text-center">Orçamentos</h5>
                        <span class="home-contato-text center-block text-center">example@example.com</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

SistemaFinanceiro/Views/Shared/_Footer.cshtml
<footer id="footer" class="container-fluid">

    <div class="footer-main">
        <div class="container">
            <div class="row">
                <div class="footer-col col-md-4 col-sm-4 col-xs-12">
                    <span class="footer-main-logo"><img src="~/images/logotipoconstrutora5.png" width="150" alt="Construtora Logo" /></span>
                    <span class="footer-main-social">
                        <a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook-official"></i></a>
                        <a href="https://www.instagram.com" target="_blank"><i class="fa fa-instagram"></i></a>
                        <a href="https://www.linkedin.com" target="_blank"><i class="fa fa-linkedin-square"></i></a>
                    </span>
                    <span class="footer-main-info">
                        Construtora Fulano de Tal<br />
                        CNPJ 00.000.000/0000-00<br />
                    </span>
                </div>
                <div class="footer-col col-md-4 col-sm-4 col-xs-12">
                    <span class="footer-main-title">Sobre</span>
                    <div class="footer-main-line"></div>
                    <ul>
                        <li><a class="page-scroll" href="/#quem">Quem Somos</a></li>
                        <li><a class="page-scroll" href="/#informacoes">Plantas Baixa</a></li>
                        <li><a class="page-scroll" href="/#servicos">Serviços</a></li>
                        <li><a class="page-scroll" href="/#contato:;">Contato</a></li>
                    </ul>
                </div>
                <div class="footer-col col-md-4 col-sm-4 col-xs-12">
                    <span class="footer-main-title">Serviços</span>
                    <div class="footer-main-line"></div>
                    <ul>
                        <li><a href="javascript:;">Exemplo</a></li>
                        <li><a class="page-scroll" href="javascript:;">Exemplo</a></li>
                        <li><a class="page-scroll" href="javascript:;">Exemplo</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-sign">
        <div class="container">
            <div class="row">
                <div class="footer-sign-legal col-md-6 col-sm-6 col-xs-12">
                    Construtora Fulano de Tal - &copy; @DateTime.Now.Year - CNPJ: 00.000.000/0000-00.<br />
                    Todos os direitos reservados. Conheça nossa Política de Privacidade
                </div>
                <div class="footer-sign-dev col-md-6 col-sm-6 col-xs-12">
                    Desenvolvido por: &nbsp;&nbsp;&nbsp;<a href="javascript:;" target=""><img src="~/images/logotipo-dev.png" height="40" alt="" /></a>
                </div>
            </div>
        </div>
    </div>
</footer>

SistemaFinanceiro/Views/Shared/_Head.cshtml
	<!-- Meta -->
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="author" content="ac5m4ck" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="index, follow" />
<link href="https://plus.google.com/" rel="publisher" />
<title>@ViewData["Title"] - SistemaFinanceiro</title>

<environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</environment>
<link href="~/css/mvc-grid/mvc-grid.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="~/css/theme.css" rel="stylesheet">

SistemaFinanceiro/Views/Shared/_Informacoes.cshtml
<section id="informacoes" class="container-fluid">
    <div class="container">
        <div class="section-title col-xs-12"><h3><span>Conheça mais</span></h3></div>
        <div class="col-md-6">
            <img src="~/images/home-planta-baixa.jpg" width="500" alt="" />
        </div>
        <div class="col-md-6">
            <span class="home-informacoes-text">Lorem ipsum maximus quam non commodo. Integer maximus consectetur lacus, a volutpat nibh ornare non. Donec vestibulum purus nec finibus gravida. Etiam ac lectus rhoncus, pellentesque nisi at, ultricies metus. Curabitur lacinia orci libero, sit amet scelerisque ante hendrerit et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam tortor arcu, fermentum vitae laoreet at, eleifend in enim. Sed eget arcu libero. Praesent turpis leo, blandit eu hendrerit eu, hendrerit in velit. Donec a mi vitae velit lacinia vehicula. Fusce cursus maximus tortor, vel vestibulum est tempus eget. Donec feugiat est ac diam commodo fermentum.</span>
        </div>
        <div class="home-infomacoes-button col-md-12 col-xs-12">
            <a href="https://br.pinterest.com/literatura10bah/planta-baixa-casa">
                <span>Ver Mais Opções de Plantas  <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></span>
            </a>
        </div>
    </div>
</section>

SistemaFinanceiro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Financeiro | Construtora </title>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="css/animate.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">Financeiro</strong>
                    </li>
                   
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a></li>
                        <li><a asp-area="" asp-controller="Terceiros" asp-action="Index">Terceiros</a></li>
                        <li><a asp-area="" asp-controller="Financeiro" asp-action="Index">Financeiro</a></li>                 

            </div>

        </nav>       

        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" method="post" action="#">
                            <div class="form-group">

                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <a href="#">
                                <i class="fa fa-sign-out"></i> Acesso
                            </a>
                        </li>
                    </ul>

                </nav>
            </div>
            <div class="wrapper wrapper-content animated fadeInRight">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center m-t-lg">

                            <small>
                            </small>
                        </div>
                    </div>
                </div>
                <div class="container body-content">
                    @RenderBody()
                    <hr />
                    <footer>
                       @*<p>&copy; 2019 - SistemaFinanceiro</p>*@
                    </footer>
                </div>
            </div>
            <div class="footer">
                <div class="pull-right">

                </div>
                <div>
                    <strong>Empresa</strong>Company &copy; 2019-2019
                </div>
            </div>

        </div>

    </div>
  

    <!-- Mainly scripts -->
    <script src="js/jquery-3.1.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="js/inspinia.js"></script>
    <script src="js/plugins/pace/pace.min.js"></script>
    @RenderSection("Scripts", required: false)

</body>

</html>

SistemaFinanceiro/Views/Shared/_Nav.cshtml
<header class="navbar-wrapper">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="row">

                <div class="navbar-header col-lg-5 col-sm-5">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navBar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    <a asp-controller="Home" asp-action="Index"><img class="navbar-logo" src="~/images/logotipoconstrutora5.png" alt="Logo Construtora" /></a>
                </div>

                <div id="navBar" class="navbar-collapse collapse col-lg-4 col-sm-4">
                    <ul class="nav navbar-nav">
                        <li><a class="page-scroll" href="/#quem">Quem Somos</a></li>
                        <li><a class="page-scroll" href="/#informacoes">Plantas Baixa</a></li>
                        <li><a class="page-scroll" href="/#servicos">Serviços</a></li>
                        <li><a class="page-scroll" href="/#contato">Contato</a></li>
                    </ul>
                    </div>

                <div class="navbar-login col-lg-2 col-sm-2">
                    <div class="navbar-form" style="border-top: none; border-bottom: none;">
                        <a asp-area="" asp-controller="Acesso" asp-action="Entrar" class="btn btn-default">
                            <span class="glyphicon glyphicon-user primary"></span>
                            <span class="hidden-xs entrar">Área Administrativa</span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </nav>
</header>

SistemaFinanceiro/Views/Shared/_Painel.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="~/css/mvc-grid/mvc-grid.css" rel="stylesheet">

    <title>@ViewBag.Title - Painel Administrativo</title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SistemaFinanceiro", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", title = "Voltar ao site" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a></li>
                    <li><a asp-area="" asp-controller="Terceiros" asp-action="Index">Terceiros</a></li>
                    <li><a asp-area="" asp-controller="Financeiro" asp-action="Index">Financeiro</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @if (TempData["Sucesso"] != null)
        {
            <br />
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                @TempData["Sucesso"]
            </div>
        }

        @if (TempData["Erro"] != null)
        {
            <br />
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                @TempData["Erro"]
            </div>
        }

        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SistemaFinanceiro</p>
        </footer>
    </div>
  
    <script src="~/js/mvc-grid/mvc-grid.js"></script>
    <script src="~/js/mvc-grid/mvc-grid.util.js"></script>
</body>
</html>

SistemaFinanceiro/Views/Shared/_Quem.cshtml
<section id="quem" class="container-fluid">
    <div class="container">
        <div class="section-title col-sm-12"><h3><span>Quem Somos?</span></h3></div>
        <div class="col-sm-6 col-xs-12">
            <div class="home-quem-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed volutpat leo, vitae semper nibh. Morbi maximus libero vel orci mollis, vel dapibus nisl consequat. Vestibulum augue arcu, feugiat a erat non, porttitor posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed volutpat leo, vitae semper nibh. Morbi maximus libero vel orci mollis, vel dapibus nisl consequat. Vestibulum augue arcu, feugiat a erat non, porttitor posuere.
            </div>
        </div>
    </div>
</section>

SistemaFinanceiro/Views/Shared/_Scripts.cshtml
<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>
<script src="~/js/mvc-grid/mvc-grid.js"></script>
<link rel="stylesheet" href="~/font-awesome/css/font-awesome.css">

SistemaFinanceiro/Views/Shared/_Servicos.cshtml
<section id="servicos" class="container">
    <div class="row">
        <div class="section-title col-xs-12"><h3><span>Nossos Serviços</span></h3></div>
    </div>

    <div class="home-servicos-itens">
        <!-- ====================================================== VANTAGENS - ITEM 01 ================================================== -->
        <div class="item col-sm-4 col-xs-12">
            <span class="home-servicos-icon"><img src="~/images/home-servicos-residencias.png" width="120" height="120" alt="" /></span>
            <span class="home-servicos-title">Obras Residenciais</span>
            <span class="home-servicos-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum commodo fermentum. Etiam pulvinar ultricies dolor, quis pellentesque enim congue vitae. Nam pulvinar finibus lacinia. </span>
        </div>
        <!-- ====================================================== VANTAGENS - ITEM 02 ================================================== -->
        <div class="item col-sm-4 col-xs-12">
            <span class="home-servicos-icon"><img src="~/images/home-servicos-residencias.png" width="120" height="120" alt="" /></span>
            <span class="home-servicos-title">Obras Residenciais</span>
            <span class="home-servicos-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum commodo fermentum. Etiam pulvinar ultricies dolor, quis pellentesque enim congue vitae. Nam pulvinar finibus lacinia. </span>
        </div>
        <!-- ====================================================== VANTAGENS - ITEM 03 ================================================== -->
        <div class="item col-sm-4 col-xs-12">
            <span class="home-servicos-icon"><img src="~/images/home-servicos-residencias.png" width="120" height="120" alt="" /></span>
            <span class="home-servicos-title">Obras Residenciais</span>
            <span class="home-servicos-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum commodo fermentum. Etiam pulvinar ultricies dolor, quis pellentesque enim congue vitae. Nam pulvinar finibus lacinia. </span>
        </div>
        <div class="home-servicos-button col-sm-12 col-xs-12">
            <a asp-area="" asp-controller="" asp-action="">
                <span class="hidden-xs">Conheça Nossas Obras</span>
            </a>
        </div>
    </div>
</section>